### ISSUE TITLE
Is this library still recommended for use in development or is it no longer maintained?

### ISSUE THREAD

**Issue by cboettig** [msporny/libjsonld#1]
Hi @msporny,

Apologies if the question seems impertinent, but seems one could hardly do better than using your own implementation of jsonld parser. Yet with the last commit 6 years ago gives one pause.  Is there a more actively maintained libjsonld library that you would recommend using when, for instance, building out jsonld tools for other languages?  Seems other implementations (ruby, python) are just each writing their doing native implementations instead?

Thanks for your thoughts!

**Comment by msporny** [comment]
The list of JSON-LD parsers you should use are here: http://json-ld.org/

Sorry, not enough time to maintain list library, closing this repo down.
